package evolution

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// IngestedEvents is the event subscription the gateway depends on. MESSAGE and
// SEND_MESSAGE carry both sides of every conversation, HISTORY_SYNC carries the
// on-demand backfill, and CONNECTION carries the instance state that would
// otherwise have to be polled.
var IngestedEvents = []string{"MESSAGE", "SEND_MESSAGE", "HISTORY_SYNC", "CONNECTION"}

// ErrLoggedIn reports that the instance already has a paired WhatsApp session,
// so there is no QR code to scan.
var ErrLoggedIn = errors.New("instance is already logged in")

// QRCode carries the pairing payload. Image is a ready-to-render
// "data:image/png;base64,..." URI produced by Evolution itself; Code is the raw
// string behind it, useful for pairing flows that do not scan an image.
type QRCode struct {
	Image string `json:"qrcode"`
	Code  string `json:"code"`
}

// State is the live connection state of a single instance.
type State struct {
	Connected bool   `json:"Connected"`
	LoggedIn  bool   `json:"LoggedIn"`
	Name      string `json:"Name"`
}

// call performs one Evolution request authenticated with the given key. The
// global key answers for administrative routes; every per-instance route is
// authenticated with that instance's own token, because Evolution resolves the
// target instance from the key and accepts no instance parameter.
func (c *Client) call(ctx context.Context, method, path, key string, body, out any) error {
	endpoint, err := url.JoinPath(c.baseURL, path)
	if err != nil {
		return err
	}
	var payload io.Reader
	if body != nil {
		encoded, err := json.Marshal(body)
		if err != nil {
			return err
		}
		payload = bytes.NewReader(encoded)
	}
	req, err := http.NewRequestWithContext(ctx, method, endpoint, payload)
	if err != nil {
		return err
	}
	req.Header.Set("apikey", key)
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	resp, err := c.http.Do(req)
	if err != nil {
		return fmt.Errorf("Evolution %s: %w", path, err)
	}
	defer resp.Body.Close()
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return fmt.Errorf("Evolution %s returned HTTP %d: %s", path, resp.StatusCode, reason(resp.Body))
	}
	if out == nil {
		_, _ = io.Copy(io.Discard, resp.Body)
		return nil
	}
	var envelope struct {
		Data json.RawMessage `json:"data"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&envelope); err != nil {
		return fmt.Errorf("decode Evolution %s: %w", path, err)
	}
	if len(envelope.Data) == 0 {
		return nil
	}
	return json.Unmarshal(envelope.Data, out)
}

// reason extracts Evolution's own error message from a failed response so the
// panel can show what went wrong instead of a bare status code. The body is
// bounded because it is remote input.
func reason(body io.Reader) string {
	raw, err := io.ReadAll(io.LimitReader(body, 4096))
	if err != nil || len(raw) == 0 {
		return "no detail"
	}
	var payload struct {
		Error   string `json:"error"`
		Message string `json:"message"`
	}
	if json.Unmarshal(raw, &payload) == nil {
		if detail := first(payload.Error, payload.Message); detail != "" {
			return detail
		}
	}
	return strings.TrimSpace(string(raw))
}

// CreateInstance registers a new instance under the global key. The token is
// chosen by this gateway and becomes the credential for every later
// per-instance call, so it is generated by the caller and stored locally.
func (c *Client) CreateInstance(ctx context.Context, name, token string) (Instance, error) {
	var created struct {
		ID           string `json:"id"`
		InstanceID   string `json:"instanceId"`
		Name         string `json:"name"`
		InstanceName string `json:"instanceName"`
	}
	body := map[string]any{"name": name, "token": token}
	if err := c.call(ctx, http.MethodPost, "/instance/create", c.apiKey, body, &created); err != nil {
		return Instance{}, err
	}
	id := first(created.ID, created.InstanceID, created.Name, created.InstanceName, name)
	return Instance{ID: id, Name: first(created.Name, created.InstanceName, name), Status: StatusDisconnected}, nil
}

// DeleteInstance removes the instance from Evolution. It is an administrative
// route, so it uses the global key and the instance id in the path.
func (c *Client) DeleteInstance(ctx context.Context, instanceID string) error {
	return c.call(ctx, http.MethodDelete, "/instance/delete/"+url.PathEscape(instanceID), c.apiKey, nil, nil)
}

// ConnectInstance starts the WhatsApp client and wires it to the RabbitMQ
// queues. Passing "global" for rabbitmqEnable is what makes Evolution publish
// at all: its producer drops every event when that field is unset.
func (c *Client) ConnectInstance(ctx context.Context, token string) error {
	body := map[string]any{"subscribe": IngestedEvents, "rabbitmqEnable": "global"}
	return c.call(ctx, http.MethodPost, "/instance/connect", token, body, nil)
}

// DisconnectInstance stops the client without dropping the WhatsApp session, so
// reconnecting needs no new QR code.
func (c *Client) DisconnectInstance(ctx context.Context, token string) error {
	return c.call(ctx, http.MethodPost, "/instance/disconnect", token, map[string]any{}, nil)
}

// LogoutInstance ends the WhatsApp session itself. Pairing again requires a new
// QR code.
func (c *Client) LogoutInstance(ctx context.Context, token string) error {
	return c.call(ctx, http.MethodDelete, "/instance/logout", token, nil, nil)
}

// QRCode returns the pairing code for an instance that is not yet paired.
func (c *Client) QRCode(ctx context.Context, token string) (QRCode, error) {
	var code QRCode
	err := c.call(ctx, http.MethodGet, "/instance/qr", token, nil, &code)
	if err != nil && strings.Contains(strings.ToLower(err.Error()), "logged in") {
		return QRCode{}, ErrLoggedIn
	}
	return code, err
}

// State reports the live connection state of one instance.
func (c *Client) State(ctx context.Context, token string) (State, error) {
	var state State
	err := c.call(ctx, http.MethodGet, "/instance/status", token, nil, &state)
	return state, err
}
